name: dagger
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@v6
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_TOKEN }}
        with:
          version: "latest"
          dagger-flags: "-vvv --progress plain"
          verb: call
          args: testit --source=.
